# Generated by Django 2.0.6 on 2018-07-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('price', models.IntegerField(blank=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('image_main', models.ImageField(upload_to='')),
            ],
        ),
    ]
