# Generated by Django 2.0.6 on 2018-07-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop_item',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='shop_item',
            name='url',
            field=models.FilePathField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='shop_item',
            name='image_main',
            field=models.ImageField(upload_to='for_sale'),
        ),
    ]
