# Generated by Django 2.0.6 on 2018-07-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180709_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_item',
            name='image_main',
            field=models.ImageField(upload_to='static/for_sale'),
        ),
    ]
