# Generated by Django 2.0.6 on 2018-07-09 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180709_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_item',
            name='name',
        ),
        migrations.RemoveField(
            model_name='shop_item',
            name='url',
        ),
    ]
