# Generated by Django 2.0.6 on 2018-07-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_shop_item_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_item',
            name='url',
            field=models.CharField(default='for_sale/', max_length=100),
        ),
    ]
