# Generated by Django 2.0.6 on 2018-07-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20180711_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_item',
            name='product_url',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
