# Generated by Django 2.0.6 on 2018-07-11 17:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20180711_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_item',
            name='product_url',
            field=models.CharField(default=uuid.UUID('08c23383-d505-4c11-839a-7e2a660a168a'), max_length=100),
        ),
    ]
