# Generated by Django 2.0.6 on 2018-07-11 17:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20180711_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_item',
            name='product_url',
            field=models.CharField(default=uuid.UUID('686a7f2f-cd4a-4097-8ccd-d33054f4431d'), max_length=100),
        ),
    ]
