# Generated by Django 2.0.6 on 2018-07-11 17:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20180711_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_item',
            name='product_url',
            field=models.CharField(default=uuid.UUID('0dce6aec-57df-481a-aa22-2994f162dfac'), max_length=100, unique=True),
        ),
    ]
