# Generated by Django 2.0.6 on 2018-07-12 07:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20180711_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_item',
            name='product_url',
            field=models.CharField(default=uuid.UUID('2b87b14e-8f99-4aee-b749-3dc0c90eaf54'), max_length=100, unique=True),
        ),
    ]
