# Generated by Django 2.1 on 2018-08-07 04:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20180712_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_item',
            name='product_url',
            field=models.CharField(default=uuid.UUID('f5df4ef8-b342-4648-a4a2-9f29e7b54456'), max_length=100, unique=True),
        ),
    ]
