# Generated by Django 2.1 on 2018-08-07 04:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20180807_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_item',
            name='product_url',
            field=models.CharField(default=uuid.UUID('94cbe915-b7b4-4589-802c-3203b62ebe2b'), max_length=100, unique=True),
        ),
    ]
