# Generated by Django 2.1 on 2018-08-07 04:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20180807_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_item',
            name='product_url',
            field=models.CharField(default=uuid.UUID('db4d5782-8be4-4493-98f0-7fe3d59d7873'), max_length=100, unique=True),
        ),
    ]
