# Generated by Django 2.1 on 2018-08-07 04:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20180807_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_item',
            name='product_url',
            field=models.CharField(default=uuid.UUID('5dd00af3-bc5b-4f5a-ad2d-2264646864d3'), max_length=100, unique=True),
        ),
    ]
